# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app2.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1132, 782)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.union_2 = QtWidgets.QPushButton(self.centralwidget)
        self.union_2.setGeometry(QtCore.QRect(320, 130, 211, 31))
        self.union_2.setObjectName("union_2")
        self.intersection = QtWidgets.QPushButton(self.centralwidget)
        self.intersection.setGeometry(QtCore.QRect(320, 170, 211, 31))
        self.intersection.setObjectName("intersection")
        self.difference = QtWidgets.QPushButton(self.centralwidget)
        self.difference.setGeometry(QtCore.QRect(320, 210, 211, 31))
        self.difference.setObjectName("difference")
        self.new_set_btn = QtWidgets.QPushButton(self.centralwidget)
        self.new_set_btn.setGeometry(QtCore.QRect(320, 290, 211, 31))
        self.new_set_btn.setObjectName("new_set_btn")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(10, 130, 301, 601))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 299, 599))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.gridLayout = QtWidgets.QGridLayout(self.scrollAreaWidgetContents)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.set_elements_label = QtWidgets.QLabel(self.centralwidget)
        self.set_elements_label.setGeometry(QtCore.QRect(540, 10, 411, 21))
        self.set_elements_label.setObjectName("set_elements_label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 110, 81, 21))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 110, 81, 21))
        self.label_3.setObjectName("label_3")
        self.hint_label = QtWidgets.QLabel(self.centralwidget)
        self.hint_label.setGeometry(QtCore.QRect(10, 0, 521, 21))
        self.hint_label.setAlignment(QtCore.Qt.AlignCenter)
        self.hint_label.setObjectName("hint_label")
        self.assign_btn = QtWidgets.QPushButton(self.centralwidget)
        self.assign_btn.setGeometry(QtCore.QRect(320, 250, 211, 31))
        self.assign_btn.setObjectName("assign_btn")
        self.equation_mark = QtWidgets.QLabel(self.centralwidget)
        self.equation_mark.setGeometry(QtCore.QRect(150, 20, 61, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.equation_mark.setFont(font)
        self.equation_mark.setAlignment(QtCore.Qt.AlignCenter)
        self.equation_mark.setObjectName("equation_mark")
        self.now_operation_label = QtWidgets.QLabel(self.centralwidget)
        self.now_operation_label.setGeometry(QtCore.QRect(330, 20, 61, 81))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.now_operation_label.setFont(font)
        self.now_operation_label.setAlignment(QtCore.Qt.AlignCenter)
        self.now_operation_label.setObjectName("now_operation_label")
        self.delete_btn = QtWidgets.QPushButton(self.centralwidget)
        self.delete_btn.setGeometry(QtCore.QRect(320, 410, 211, 31))
        self.delete_btn.setObjectName("delete_btn")
        self.assign_set_btn = QtWidgets.QPushButton(self.centralwidget)
        self.assign_set_btn.setGeometry(QtCore.QRect(32, 20, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.assign_set_btn.setFont(font)
        self.assign_set_btn.setObjectName("assign_set_btn")
        self.first_set_btn = QtWidgets.QPushButton(self.centralwidget)
        self.first_set_btn.setGeometry(QtCore.QRect(210, 20, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.first_set_btn.setFont(font)
        self.first_set_btn.setObjectName("first_set_btn")
        self.second_set_btn = QtWidgets.QPushButton(self.centralwidget)
        self.second_set_btn.setGeometry(QtCore.QRect(390, 20, 121, 81))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.second_set_btn.setFont(font)
        self.second_set_btn.setObjectName("second_set_btn")
        self.new_set_from_user_friends = QtWidgets.QPushButton(self.centralwidget)
        self.new_set_from_user_friends.setGeometry(QtCore.QRect(320, 330, 211, 31))
        self.new_set_from_user_friends.setObjectName("new_set_from_user_friends")
        self.new_set_from_community_followers = QtWidgets.QPushButton(self.centralwidget)
        self.new_set_from_community_followers.setGeometry(QtCore.QRect(320, 370, 211, 31))
        self.new_set_from_community_followers.setObjectName("new_set_from_community_followers")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(540, 30, 581, 701))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1132, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.union_2.setText(_translate("MainWindow", "Union"))
        self.intersection.setText(_translate("MainWindow", "Intersection"))
        self.difference.setText(_translate("MainWindow", "Difference"))
        self.new_set_btn.setText(_translate("MainWindow", "New set"))
        self.set_elements_label.setText(_translate("MainWindow", "Set members"))
        self.label_2.setText(_translate("MainWindow", "Sets"))
        self.label_3.setText(_translate("MainWindow", "Operations"))
        self.hint_label.setText(_translate("MainWindow", "Hint"))
        self.assign_btn.setText(_translate("MainWindow", "Assignment"))
        self.equation_mark.setText(_translate("MainWindow", "="))
        self.now_operation_label.setText(_translate("MainWindow", "Op"))
        self.delete_btn.setText(_translate("MainWindow", "Delete set"))
        self.assign_set_btn.setText(_translate("MainWindow", "Assign set"))
        self.first_set_btn.setText(_translate("MainWindow", "First set"))
        self.second_set_btn.setText(_translate("MainWindow", "Second set"))
        self.new_set_from_user_friends.setText(_translate("MainWindow", "New from user friends"))
        self.new_set_from_community_followers.setText(_translate("MainWindow", "New from community followers"))
